### ISSUE TITLE
npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by nagendrababujonna** [jsreport/jsreport-extension-starter-kit#1]
4145 warn custom-extension@1.0.0 No repository field.
4146 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
4147 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
4148 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4148 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4148 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4148 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4149 verbose stack Error: node-sass@3.7.0 postinstall: `node scripts/build.js`
4149 verbose stack Exit status 1
4149 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
4149 verbose stack     at EventEmitter.emit (events.js:182:13)
4149 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4149 verbose stack     at ChildProcess.emit (events.js:182:13)
4149 verbose stack     at maybeClose (internal/child_process.js:962:16)
4149 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by pofider** [comment]
This works for me on windows. 
git clone...
npm i

What is your npm version?
Do you have these windows [prerequisites](https://github.com/nodejs/node-gyp#on-windows)
